name: Comvent - Run if comment matches the keyword
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/comvent@v0.1.0
        id: comvent
        with:
          keyword: Trigger # This is the regex string to match against
      - name: Some random step
        run: |
          echo This step simply runs, as there is no condition check
      - name: Run when comvent matches
        run: |
          echo You see this step run only when comvent found the matching keyword in the comment event
        if: steps.comvent.outputs.comvent != ''
