name: Comvent - Check against multiple criteria
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/comvent@v0.1.0
        id: comvent-0000
        with:
          keyword: 0000

      - uses: rytswd/comvent@v0.1.0
        id: comvent-1111
        with:
          keyword: 1111

      - name: Keyword 0000 found in comment
        run: echo This step runs when the first keyword "0000" matches the comment
        if: steps.comvent-abc.outputs.comvent != ''

      - name: Keyword 1111 found in comment
        run: echo This step runs when the second keyword "1111" matches the comment
        if: steps.comvent-def.outputs.comvent != ''

      - uses: rytswd/comvent@v0.1.0
        id: comvent-follow-up
        with:
          keyword: "^Test" # Regex search, case sensitive
        if: steps.comvent-abc.outputs.comvent == '' && steps.comvent-def.outputs.comvent == ''

      - name: Keyword "^Test" found in comment
        run: echo This step only runs when the comment does not have "0000" or "1111", and instead starts with "Test"
        if: steps.comvent-follow-up.outputs.comvent != ''
